project_id = "tkyyhbvxxvtgxizkecso"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"
tenant_id = "realtime-dev"
max_concurrent_users = 200
max_events_per_second = 100
max_channels_per_client = 100
max_joins_per_second = 100
max_messages_per_second = 100
enable_jwt_validations = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = true

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
template = {}

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your OTP is {{ .Code }}"

[edge_runtime]
enabled = true
ip_version = "ipv6"
policy = "per_worker"
inspector_port = 8083

[analytics]
enabled = false
port = 54327
vector_port = 54328
gw_mode = "disabled"

[functions.generate-ai-workout]
verify_jwt = true

[functions.search-youtube-videos]
verify_jwt = true

[functions.analyze-food-image]
verify_jwt = true