// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkyyhbvxxvtgxizkecso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRreXloYnZ4eHZ0Z3hpemtlY3NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDk1NzksImV4cCI6MjA3MzkyNTU3OX0.BKy2VNpriSJeiXZPGPl0ZW_HhfhSe9yeS_OV9qptUg8";

// Import the supabase client like this:
// import { supabase } from "@/core/services/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
